exports.slugs  = [
    { "slug": "introduction-to-overops", "id": "", "name": "Introduction to OverOps" },
    { "slug": "whats-new", "id": null, "name": "What's New" },
    { "slug": "compatibility", "id": null, "name": "Getting Started" },
    { "slug": "reliability-dashboards-overview", "id": "", "name": "Reliability Dashboards" },
    { "slug": "automated-root-cause-arc", "id": "", "name": "Resolving Errors" },
    { "slug": "overops-install-portal-deployment-models", "id": "", "name": "Installation" },
    { "slug": "the-dashboard-overview", "id": "", "name": "Classic  Dashboard" },
    { "slug": "advanced-settings-1", "id": "", "name": "Advanced Configuration" },
    { "slug": "collector-properties", "id": "", "name": "Collector Advanced Settings" },
    { "slug": "agent-properties", "id": "", "name": "Agents Advanced Settings" },
    { "slug": "upgrading-overops", "id": "", "name": "Upgrading or Uninstalling OverOps" },
    { "slug": "installation-site-map", "id": "", "name": "Installation Links" },
    { "slug": "configure-your-integrations", "id": "", "name": "Integrations" },
    { "slug": "publishing-metrics", "id": "", "name": "Reporting and Publishing Metrics" },
    { "slug": "overops-security-protocols", "id": "", "name": "Security" },
    { "slug": "build-tools", "id": "", "name": "Build Tools" },
    { "slug": "deployment-automation", "id": "", "name": "Deployment Automation" },
    { "slug": "naming-your-application-server-deployment", "id": "", "name": "OverOps Switches" },
    { "slug": "account-settings", "id": "", "name": "Adminstration Settings" },
    { "slug": "attach-a-micro-agent", "id": "", "name": "Attaching the Agent" },
    { "slug": "overops-tutorials", "id": "", "name": "Tutoricals" }
];